/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package DataPasien;

import DataPasien.DataPasien;
import DataPasien.InsertDialog;
import pbo_sql.Koneksi;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class DeleteDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeleteDialog.class.getName());

    /**
     * Creates new form DeleteDialog
     */
    public DeleteDialog(java.awt.Frame parent, boolean modal, String Id_Pasien) {
        super(parent, modal);
        initComponents();
        jlabelDelete.setText(Id_Pasien);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlabelDelete = new javax.swing.JLabel();
        jYa = new javax.swing.JButton();
        jTidak = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(182, 206, 192));
        jPanel1.setForeground(new java.awt.Color(182, 206, 192));

        jlabelDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelDelete.setForeground(new java.awt.Color(255, 255, 255));
        jlabelDelete.setText("> ");

        jYa.setBackground(new java.awt.Color(249, 245, 234));
        jYa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jYa.setForeground(new java.awt.Color(120, 134, 107));
        jYa.setText("Ya");
        jYa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jYaActionPerformed(evt);
            }
        });

        jTidak.setBackground(new java.awt.Color(249, 245, 234));
        jTidak.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTidak.setForeground(new java.awt.Color(120, 134, 107));
        jTidak.setText("Tidak");
        jTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidakActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("APAKAH ANDA YAKIN INGIN MENGHAPUS DATA ?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jYa)
                        .addGap(45, 45, 45)
                        .addComponent(jTidak)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlabelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jYa)
                    .addComponent(jTidak))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jYaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jYaActionPerformed
        try {
            Class.forName("org.postgresql.Driver"); // ganti dengan org.postgresql.Driver kalau pakai PostgreSQL
            Connection conn = DriverManager.getConnection(
                "jdbc:postgresql://localhost:5432/PBO_P4", // URL database
                "postgres", // user database
                "karina" // password database
            );
            String sql = "DELETE FROM data_pasien WHERE Id_Pasien = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, jlabelDelete.getText().trim());

            int rows = pst.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");

                // refresh tabel di JFrame utama
                if (getParent() instanceof DataPasien) {
                    ((DataPasien) getParent()).tampilkanData();
                }
                dispose(); // tutup dialog
            } else {
                JOptionPane.showMessageDialog(this, "ID Nasabah tidak ditemukan!");
            }
            pst.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
            e.printStackTrace();
        }                           

    }//GEN-LAST:event_jYaActionPerformed

    private void jTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidakActionPerformed
        dispose();
    }//GEN-LAST:event_jTidakActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jTidak;
    private javax.swing.JButton jYa;
    private javax.swing.JLabel jlabelDelete;
    // End of variables declaration//GEN-END:variables
}
